[package]
name = "rust-build"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "build_index"
path = "src/build_index.rs"

[[bin]]
name = "expected"
path = "src/bin/expected.rs"

[dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
